// Unit imagery, served out of the archive's blob container.
//
// Two kinds:
//   cards/<unitId>.png   the rendered Alpha Strike card — the thing you print
//                        and put on the table. Generated by the Master Unit
//                        List before it shut down and impossible to recreate.
//   art/<sha1>.png       unit artwork, keyed by the sha1 of its source url so
//                        the many variants sharing one picture share one blob.
//
// Blobs are proxied rather than handed out as SAS links: the container stays
// private, the member check stays in one place, and the club's traffic is small
// enough that the bandwidth does not matter. Responses are marked immutable so
// browsers fetch each image once.

const { createHash } = require('node:crypto');
const { BlobServiceClient, StorageSharedKeyCredential } = require('@azure/storage-blob');

const ACCOUNT = process.env.MUL_STORAGE_ACCOUNT || '';
const KEY = process.env.MUL_STORAGE_KEY || '';
const CONTAINER = process.env.MUL_STORAGE_CONTAINER || 'mul-archive';

let container = null;

function available() {
  return Boolean(ACCOUNT && KEY);
}

function getContainer() {
  if (!available()) throw new Error('Media storage is not configured (MUL_STORAGE_ACCOUNT/KEY).');
  if (!container) {
    const client = new BlobServiceClient(
      `https://${ACCOUNT}.blob.core.windows.net`,
      new StorageSharedKeyCredential(ACCOUNT, KEY),
    );
    container = client.getContainerClient(CONTAINER);
  }
  return container;
}

// Blob names are built here, never taken from the request, so a crafted unit id
// cannot walk out of the container.
const cardBlob = (unitId) => `cards/${Number(unitId)}.png`;
const artBlob = (sourceUrl) => `art/${createHash('sha1').update(String(sourceUrl)).digest('hex')}.png`;

async function fetchBlob(name) {
  const blob = getContainer().getBlockBlobClient(name);
  try {
    return await blob.downloadToBuffer();
  } catch (err) {
    if (err.statusCode === 404) return null;
    throw err;
  }
}

// Send a blob as an image response, or 404 cleanly when the archive has no
// image for that unit -- six cards never existed because the source site's own
// renderer failed on them, and some units have no artwork at all.
async function send(res, name) {
  const buf = await fetchBlob(name);
  if (!buf) {
    res.status(404).json({ error: 'no image archived for that unit' });
    return;
  }
  res.set({
    'Content-Type': 'image/png',
    'Content-Length': String(buf.length),
    'Cache-Control': 'private, max-age=31536000, immutable',
  });
  res.end(buf);
}

module.exports = { available, cardBlob, artBlob, send };
